version: '3.1'

services:
  nginx:
       build:
        context: .
       container_name: nginx
       ports:
         - "8080:80"
       volumes:
         - nginxguvi:/var/opt/nginx

volumes:
     nginxguvi:

